version: '3'

services:
  web:
    image: gitea/gitea:latest
    restart: always
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - /var/lib/gitea:/data
    environment:
      APP_NAME: Gitea
      DB_TYPE: mysql
      DB_HOST_FILE: /etc/gitea_env
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea_password
